### ISSUE TITLE
harvest-space?? - hit the button to find supernodes with free slots

### ISSUE THREAD

**Issue by HaoCHEN3** [csleary/nemp3-ruby#37]
Hi,
Confused about the code part 'harvesting-space' in app.rb
Could you explain what this part code does?

thx

**Comment by csleary** [comment]
Hi! That was implemented so people could find nodes with harvesting space while the Telegram bot was down. It's not linked from the main site, but is accessed [here](https://nemp3.herokuapp.com/harvesting-space).

It queries the supernodes for free harvesting slots, displaying the first five nodes that it finds with free slots.

**Comment by HaoCHEN3** [comment]
hi, I clicked the link and tried it. Now, I definitely know what your code has done. However, I check the NIS 
 API [unlocked/info](https://bob.nem.ninja/docs/#retrieving-the-unlock-info) which you used in code. For my understanding, /unlocked/info shows the result of delegated harvest info (like the maximum number of allowed harvesters and the number of harvesters that are already using this nis node) and shows nothing about free slots?  Is it correct?

**Comment by csleary** [comment]
Yep, that's correct. The query returns the number of harvesting slots that have already been unlocked (i.e. how many are currently harvesting), as well as the maximum number of slots configured by the server, so we just subtract the maximum from the number unlocked to get our number of free slots.

**Comment by HaoCHEN3** [comment]
Yup, it makes sense. I mixed the concept of harvest free slots and unconfirmed tx free slots in NIS.
